### ISSUE TITLE
[Android Bootcamp] Project 1 - Review my SimpleToDo app

### ISSUE THREAD

**Issue by lita** [lita/SimpleToDoApp#1]
I have a working app and would like a review. 

I had a question about what the conventions for sending codes between activities and sub-activities. I assume there is something similar to the HTTP protocol.

I would also like to learn more about debuggers, and what is the most effective way to debug.

/cc @codepathreview @codepath

**Comment by nidhi1608** [comment]
Lita,

Looks good, this exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project.

> I had a question about what the conventions for sending codes between activities and sub-activities. I assume there is something similar to the HTTP protocol.

The most popular way to send data between component in Android is through Intents. Check out our detailed guide on sending and receiving data [using intents](http://guides.codepath.com/android/Using-Intents-to-Create-Flows).

>  I would also like to learn more about debuggers, and what is the most effective way to debug.

Check out this article on [debugging with Android Studio](http://developer.android.com/tools/debugging/debugging-studio.html).

The next step is to continue working on [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo) and to <b>schedule a short 5-10 minute phone conversation</b> [here](https://www.google.com/calendar/selfsched?sstoken=UU5IOEduOWEtRDg5fGRlZmF1bHR8NWRiNTI5ZWJmMjVjODg1OGVhMmU0NDg5Nzc2NDRlNTc). Navigate to [today's date and onward from there](https://www.google.com/calendar/selfsched?sstoken=UU5IOEduOWEtRDg5fGRlZmF1bHR8NWRiNTI5ZWJmMjVjODg1OGVhMmU0NDg5Nzc2NDRlNTc) and choose a 15-minute slot. Let us know if none of those times work.

Once you select a slot, can you make sure to include best number to reach you at to the invite? Look forward to chatting soon!

**Comment by lita** [comment]
Hi @nidhi1608,

I finished some extensions, and thus finished my submission. I have updated the README.md with the list of new features and a new gif. 

https://github.com/lita/SimpleToDoApp/blob/master/README.md
